parameters:
    aequasi.view_model.annotation.driver.class: Aequasi\Bundle\ViewModelBundle\Annotation\Driver\AnnotationDriver

services:
    aequasi.view_model.annotation.driver:
        class: %aequasi.view_model.annotation.driver.class%
        arguments: [@annotation_reader]
        tags: [{name: kernel.event_listener, event: kernel.controller, method: onKernelController}]
